{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kargo-event-router.fullname" . }}
  labels:
    {{- include "kargo-event-router.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - list
  - watch
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - kargo-event-router.io
  resources:
  - eventrouters
  - messagechannels
  verbs:
  - get
  - list
  - watch
{{- if .Values.metrics.initialize }}
# Required by the metrics initializer to read Kargo Stages.
- apiGroups:
  - kargo.akuity.io
  resources:
  - stages
  verbs:
  - get
  - list
  - watch
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kargo-event-router.fullname" . }}
  labels:
    {{- include "kargo-event-router.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kargo-event-router.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "kargo-event-router.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- if .Values.leaderElection.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kargo-event-router.fullname" . }}-leader-election
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kargo-event-router.labels" . | nindent 4 }}
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kargo-event-router.fullname" . }}-leader-election
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kargo-event-router.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kargo-event-router.fullname" . }}-leader-election
subjects:
- kind: ServiceAccount
  name: {{ include "kargo-event-router.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}
