{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kargo-event-router.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kargo-event-router.labels" . | nindent 4 }}
{{- end }}
