apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kargo-event-router
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - list
  - watch
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - kargo-event-router.io
  resources:
  - eventrouters
  - messagechannels
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kargo-event-router
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kargo-event-router
subjects:
- kind: ServiceAccount
  name: kargo-event-router
  namespace: kargo-event-router
---
# Only needed when ENABLE_LEADER_ELECTION=true.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kargo-event-router-leader-election
  namespace: kargo-event-router
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kargo-event-router-leader-election
  namespace: kargo-event-router
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kargo-event-router-leader-election
subjects:
- kind: ServiceAccount
  name: kargo-event-router
  namespace: kargo-event-router
